USE warehouse MONGOOSE_WH;
USE database MONGOOSE_DB;

-- Vytvorenie schemy
CREATE schema projekt_schema;
USE schema projekt_schema;

-- Vytvorenie staging tabulky
CREATE OR REPLACE TABLE FLIGHT_STATUS_LATEST_staging AS
SELECT *
FROM OAG_FLIGHT_STATUS_DATA_SAMPLE.PUBLIC.FLIGHT_STATUS_LATEST_SAMPLE;

-- Výpis prvých 10 riadkov na overenie
SELECT * FROM FLIGHT_STATUS_LATEST_staging LIMIT 10;



--LOAD
-- Tabulka dim_airline staging
CREATE OR REPLACE TABLE dim_airline_staging AS
SELECT 
    IATA_CARRIER_CODE,
    ICAO_CARRIER_CODE
FROM FLIGHT_STATUS_LATEST_STAGING
WHERE IATA_CARRIER_CODE IS NOT NULL;

SELECT * FROM dim_airline_staging;


-- Tabulka dim_airport_staging
CREATE OR REPLACE TABLE dim_airport_staging AS
    SELECT DEPARTURE_IATA_AIRPORT_CODE AS IATA_AIRPORT_CODE
FROM FLIGHT_STATUS_LATEST_STAGING
UNION ALL
    SELECT ARRIVAL_IATA_AIRPORT_CODE
FROM FLIGHT_STATUS_LATEST_STAGING;

SELECT * FROM dim_airport_staging;


-- Tabulka dim_date staging
CREATE OR REPLACE TABLE dim_date_staging AS
    SELECT DISTINCT
        SCHEDULED_DEPARTURE_DATE_LOCAL AS date
FROM FLIGHT_STATUS_LATEST_STAGING
WHERE SCHEDULED_DEPARTURE_DATE_LOCAL IS NOT NULL;

SELECT * FROM dim_date_staging;


-- Tabulka dim_time_staging
CREATE OR REPLACE TABLE dim_time_staging AS
    SELECT SCHEDULED_DEPARTURE_TIME_LOCAL AS time_val
FROM FLIGHT_STATUS_LATEST_STAGING
WHERE SCHEDULED_DEPARTURE_TIME_LOCAL IS NOT NULL
UNION ALL
    SELECT SCHEDULED_ARRIVAL_TIME_LOCAL
FROM FLIGHT_STATUS_LATEST_STAGING
WHERE SCHEDULED_ARRIVAL_TIME_LOCAL IS NOT NULL;

SELECT * FROM dim_time_staging;


-- Tabulka dim_flight_state_staging
CREATE OR REPLACE TABLE dim_flight_state_staging AS
SELECT FLIGHT_STATE
FROM FLIGHT_STATUS_LATEST_STAGING;

SELECT * FROM dim_flight_state_staging;
